version: '2.2'
services:
  superset:
    image: apache/superset
    name: "superset"
    ports:
      - 8080:8080

  cube:
    image: cubejs/cube:latest
    ports:
      - 4000:4000
      - 3306:3306
    env_file: .env
    volumes:
      - .:/cube/conf
